apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  labels:
    app: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: aoyako/service-main:latest
          ports:
            - containerPort: 8090
              name: profile
            - containerPort: 8091
              name: match
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: aoyako/service-chat:latest
          ports:
            - containerPort: 5566
              name: grpc
            - containerPort: 5567
              name: grpc-web
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: service-main
  labels:
    app: service-main
spec:
  selector:
    app: main
  ports:
    - name: profile
      port: 8090
    - name: match
      port: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: service-chat
  labels:
    app: service-chat
spec:
  type: NodePort
  selector:
    app: chat
  ports:
    - name: grpc
      port: 5566
    - name: grpc-web
      port: 5567